#!/bin/bash

source .scripts/utils.sh

exec_help() {
  echo ">> Executable subcommands list:"
  echo " > -h, --help, help             |  Print this commands information block;"
  echo " > -e, endpoints                |  Build endpoints modules to build [You can write name of endpoint as 0 parameter];"
  echo " > -a, assemblyEndpoints        |  Configure services modules before build [You can write name of endpoint as 0 parameter];"
  echo " > -j, jar                      |  Build only maintained project modules;"
  echo " > -b, build                    |  Running full build of all modules with endpoints;"
  echo " > -t, test                     |  Running testing integration-units;"
  echo ""
  echo ">> Commands usage examples: './$APP <subcommand> <parameters>' or 'sh $APP <subcommand> <parameters>'"
}

case $1 in
    "" | "-h" | "--help" | "help")
        exec_help
        ;;
    "-a" | "assemblyEndpoints")
        source .scripts/services_assemble.sh "$2"
        ;;
    "-e" | "endpoints")
        source .scripts/services_build.sh "$2"
        source .scripts/services_assemble.sh "$2"
        ;;
    "-j" | "jar")
        source .scripts/project_build.sh
        ;;
    "-b" | "build")
        source .scripts/project_build.sh
        source .scripts/services_build.sh "$2"
        source .scripts/services_assemble.sh "$2"
        ;;
    "-t" | "test")
        source .scripts/project_testing.sh "$2"
        ;;
    *)
        echo "$PREF Unknown command: $1"
        exec_help
esac
