#!/bin/bash

source .scripts/utils.sh

exec_help() {
  echo ">> Executable subcommands list:"
  echo " > -h, --help, help             |  Print this commands information block."
  echo " > -e, endpoints                |  Build endpoints modules to build."
  echo " > -a, assemblyEndpoints        |  Configure services modules before build."
  echo " > -j, jar                      |  Build only maintained project modules."
  echo " > -b, build                    |  Run full build of all modules with endpoints."
  echo ""
  echo ">> Commands usage examples: './$APP <subcommand> <flags>' or 'sh $APP <subcommand> <flags>'"
}

case $1 in
    "" | "-h" | "--help" | "help")
        exec_help
        ;;
    "-a" | "assemblyEndpoints")
        source .scripts/config_endpoints.sh
        ;;
    "-e" | "endpoints")
        source .scripts/build_endpoints.sh
        source .scripts/config_endpoints.sh
        ;;
    "-j" | "jar")
        source .scripts/build_project.sh
        ;;
    "-b" | "--build")
        source .scripts/build_project.sh
        source .scripts/build_endpoints.sh
        source .scripts/config_endpoints.sh
        ;;
    *)
        echo "$PREF Unknown command: $1"
        exec_help
esac
