package me.moonways.bridgenet.jdbc.entity;

import lombok.*;

@Getter
@ToString
@EqualsAndHashCode
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class EntityID {

    private static final int NOT_FOUND = -1;
    private static final int NO_AUTO_GENERATED = -2;

    public static EntityID createNotFound() {
        return new EntityID(NOT_FOUND);
    }

    public static EntityID createNoAutoGenerated() {
        return new EntityID(NO_AUTO_GENERATED);
    }

    public static EntityID createGenerated(long id) {
        return new EntityID(id);
    }

    private final long id;

    public boolean isIncorrect() {
        return id <= 0;
    }

    public boolean isNotFound() {
        return id == NOT_FOUND;
    }

    public boolean isNoAutoGenerated() {
        return id == NO_AUTO_GENERATED;
    }
}
