package me.moonways.bridgenet.test.jdbc.entity;

import lombok.extern.log4j.Log4j2;
import me.moonways.bridgenet.api.inject.Inject;
import me.moonways.bridgenet.jdbc.entity.EntityID;
import me.moonways.bridgenet.jdbc.entity.EntityRepository;
import me.moonways.bridgenet.jdbc.entity.EntityRepositoryAllocator;
import me.moonways.bridgenet.test.engine.BridgenetJUnitTestRunner;
import me.moonways.bridgenet.test.engine.jdbc.entity.StatusEntity;
import me.moonways.bridgenet.test.engine.jdbc.entity.UserEntity;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Optional;

import static org.junit.Assert.assertEquals;

@Log4j2
@RunWith(BridgenetJUnitTestRunner.class)
public class JdbcEntityRepositoryTest {

    private static final StatusEntity STATUS_1 = StatusEntity.builder().name("CEO_1").build();
    private static final StatusEntity STATUS_2 = StatusEntity.builder().name("CEO_2").build();
    private static final StatusEntity STATUS_3 = StatusEntity.builder().name("CEO_3").build();

    private static final UserEntity USER_1 = UserEntity.builder().firstName("Oleg").lastName("Saburov").statusEntity(STATUS_1).build();
    private static final UserEntity USER_2 = UserEntity.builder().firstName("Piter").lastName("Parker").statusEntity(STATUS_2).build();
    private static final UserEntity USER_3 = UserEntity.builder().firstName("Mark").lastName("Zukerberg").statusEntity(STATUS_3).build();

    private EntityRepository<StatusEntity> statusRepository;
    private EntityRepository<UserEntity> userRepository;

    @Inject
    private EntityRepositoryAllocator repositoryAllocator;

    @Before
    public void setUp() {
        this.statusRepository = repositoryAllocator.allocate(StatusEntity.class);
        this.userRepository = repositoryAllocator.allocate(UserEntity.class);
    }

    @Test
    public void test_userInsert() {
        EntityID entityID = userRepository.insert(USER_2);
        assertEquals(1, entityID.getId());

        log.debug("Inserted user identify: {}", entityID);

        if (entityID.isIncorrect()) {

            if (entityID.isNotFound()) {
                log.debug("entity id is not found");
            }

            if (entityID.isNoAutoGenerated()) {
                log.debug("entity id is not auto-generated");
            }
        }
    }

    @Test
    @Ignore
    public void test_userGet() {
        Optional<UserEntity> userOptional = userRepository.searchIf(
                userRepository.newSearchMarker()
                        .withGet(UserEntity::getId, 2)
                        .withGet(UserEntity::getFirstName, "Piter"));

        log.debug("Founded user: {}", userOptional.orElse(null));
    }
}
