package me.moonways.bridgenet.test.engine.jdbc.entity;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import me.moonways.bridgenet.jdbc.dao.entity.EntityAccessible;
import me.moonways.bridgenet.jdbc.dao.entity.EntityAutoGenerated;
import me.moonways.bridgenet.jdbc.dao.entity.EntityElement;

@Getter
@Builder
@ToString
@EqualsAndHashCode
@EntityAccessible(name = "Users")
public class User {

    @EntityAutoGenerated
    private long id;

    @EntityElement(order = 2)
    private String lastName;

    @EntityElement(order = 1)
    private String firstName;

    @EntityElement
    private Status status;
}
