package me.moonways.bridgenet.jdbc.dao.entity;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@Builder(toBuilder = true)
public class Element {

// ============================== // BYTE MASKS // ======================================== //

    public static final byte AUTO_GENERATED = 0x01;
    public static final byte PRIMARY = 0x02;

    public static final byte FINALIZED = 0x04;

    public static final byte UNIQUE = 0x08;

// ============================== // BYTE MASKS // ======================================== //

    private final int mask;

    @EqualsAndHashCode.Include
    private final int order;

    @EqualsAndHashCode.Include
    private final String shortName, fieldName;
    private final String defaultValue;

    private final Object value;

    @EqualsAndHashCode.Include
    private final Class<?> type;

    public boolean isAutoGenerated() {
        return hasMask(AUTO_GENERATED);
    }

    public boolean isPrimary() {
        return hasMask(PRIMARY);
    }

    public boolean isFinalized() {
        return hasMask(FINALIZED);
    }

    public boolean isUnique() {
        return hasMask(UNIQUE);
    }

    private boolean hasMask(byte mask) {
        return (this.mask & mask) == mask;
    }
}
